apiVersion: v1
kind: Service
metadata:
  name: my-service # name of the service
spec:
  type: NodePort # Service type
  selector:
    app: nginx # label of your pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
